#!/bin/bash

set -x

g++ -I/opt/protobuf/include -I./generated -c generated/delta/d.pb.cc
g++ -I/opt/protobuf/include -I./generated -c generated/gamma/g.pb.cc
g++ -I/opt/protobuf/include -I./generated -c generated/eta/e.pb.cc
g++ -I/opt/protobuf/include -I./generated -c generated/eta/zeta/z.pb.cc
g++ -I/opt/protobuf/include -I./generated -c generated/eta/zeta/theta/t.pb.cc
g++ -I/opt/protobuf/include -I./generated -o main main.cc d.pb.o g.pb.o e.pb.o z.pb.o t.pb.o -L/opt/protobuf/lib -lprotobuf -lprotoc

