#!/bin/bash

set -x

protoc --proto_path ./protobuf --cpp_out cpp/generated protobuf/*/*.proto

protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'import_from_package=alpha.beta' protobuf/*/*.proto

