#!/bin/bash

set -x

protoc --proto_path ./protobuf --cpp_out cpp/generated protobuf/*.proto

protoc --proto_path ./protobuf --python_out python/omega --python_opt 'replace_import_package=|.' protobuf/*.proto

