#!/bin/bash

set -x

protoc --proto_path ./protobuf --cpp_out cpp/generated protobuf/*.proto

protoc --proto_path ./protobuf --python_out python/omega --python_opt 'import_from_package=.' protobuf/*.proto

