#!/bin/bash

set -x

protoc --proto_path ./protobuf --cpp_out cpp/generated protobuf/*/*.proto
protoc --proto_path ./protobuf --cpp_out cpp/generated protobuf/eta/zeta/*.proto
protoc --proto_path ./protobuf --cpp_out cpp/generated protobuf/eta/zeta/theta/*.proto

# Either absolute package name ...
protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'import_from_package=alpha.beta' protobuf/*/*.proto
protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'import_from_package=alpha.beta' protobuf/eta/zeta/*.proto
protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'import_from_package=alpha.beta' protobuf/eta/zeta/theta/*.proto

# ... or relative paths work
#protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'import_from_package=..' protobuf/*/*.proto
#protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'import_from_package=...' protobuf/eta/zeta/*.proto
#protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'import_from_package=....' protobuf/eta/zeta/theta/*.proto

