#!/bin/bash

set -x

protoc --proto_path ./protobuf --cpp_out cpp/generated protobuf/*.proto

# Either absolute preferred package name ...
protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'replace_import_package=|alpha.beta' protobuf/*.proto

# ... or relative preferred package name works
#protoc --proto_path ./protobuf --python_out python/alpha/beta --python_opt 'replace_import_package=|.' protobuf/*.proto

