#!/bin/bash

set -x

# Generate a "system" library that our project will refer to:
pushd system
./generate
popd

# Generate C++ and Python code for our project, "zeta", changing the
# generated Python import statement for the internal project message module
# to include an explicit relative import, while leaving the generated import
# statement for the system package unchanged:
protoc \
  --proto_path './system:./protobuf' \
  --cpp_out cpp/generated \
  --python_out python/zeta \
  --python_opt 'replace_import_package=|.' \
  protobuf/*.proto

